# Generated by Django 4.2.30 on 2026-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STORE_MANAGER", "Store Manager"),
                    ("SALES_MANAGER", "Sales Manager"),
                    ("PURCHASE_MANAGER", "Purchase Manager"),
                ],
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
