# Generated by Django 6.1 on 2026-08-14 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_partner_name', models.CharField(max_length=255)),
                ('exchange_date', models.DateField()),
                ('amount_irr_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('foreign_currency_code', models.CharField(max_length=10)),
                ('foreign_amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_from', to='finance.financialaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_to', to='finance.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('IN', 'Inflow'), ('OUT', 'Outflow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_code', models.CharField(max_length=10)),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount')),
            ],
        ),
    ]
