# Generated by Django 4.2.30 on 2026-08-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyexchange',
            old_name='foreign_currency_code',
            new_name='to_currency_code',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='amount_irr_paid',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='foreign_amount_received',
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='from_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='from_currency_code',
            field=models.CharField(default='IRR', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='to_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='parties.financialaccount'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PROCUREMENT', 'Procurement'), ('SALES', 'Sales')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_from', to='parties.financialaccount'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_to', to='parties.financialaccount'),
        ),
    ]
