# Generated by Django 4.2.30 on 2026-08-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_payment_customer_payment_created_at_and_more'),
        ('finance', '0002_rename_foreign_currency_code_currencyexchange_to_currency_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
    ]
