# Generated by Django 4.2.30 on 2026-08-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_delete_financialaccount"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="accounttransaction",
            table="account_transactions",
        ),
        migrations.AlterModelTable(
            name="currencyexchange",
            table="currency_exchanges",
        ),
    ]
