# Generated by Django 4.2.30 on 2026-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_accounttransaction_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransaction",
            name="currency_code",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="currencyexchange",
            name="from_currency_code",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="currencyexchange",
            name="to_currency_code",
            field=models.CharField(max_length=3),
        ),
    ]
