# Generated by Django 4.2.30 on 2026-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_accounttransaction_currency_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransaction",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROCUREMENT", "Procurement"),
                    ("SALES", "Sales"),
                    ("CURRENCY_EXCHANGE", "Currency Exchange"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="accounttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="account_transaction_amount_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyexchange",
            constraint=models.CheckConstraint(
                check=models.Q(("from_amount__gt", 0)),
                name="exchange_from_amount_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyexchange",
            constraint=models.CheckConstraint(
                check=models.Q(("to_amount__gt", 0)), name="exchange_to_amount_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyexchange",
            constraint=models.CheckConstraint(
                check=models.Q(("exchange_rate__gt", 0)), name="exchange_rate_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyexchange",
            constraint=models.CheckConstraint(
                check=models.Q(("from_account", models.F("to_account")), _negated=True),
                name="exchange_accounts_different",
            ),
        ),
    ]
