# Generated by Django 4.2.30 on 2026-09-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_accounttransaction_reference_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="accounttransaction",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROCUREMENT", "Procurement"),
                    ("SALES", "Sales"),
                    ("CURRENCY_EXCHANGE", "Currency Exchange"),
                    ("FINANCIAL_ACCOUNT", "Financial Account"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="currencyexchange",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
        migrations.AlterField(
            model_name="currencyexchange",
            name="from_amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="currencyexchange",
            name="to_amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
