# Generated by Django 4.2.30 on 2026-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
