# Generated by Django 4.2.30 on 2026-08-15 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "transfer_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_stock_transfers",
                        to="parties.warehouse",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transfers",
                        to="products.product",
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_stock_transfers",
                        to="parties.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock_transfers",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_type", models.CharField(max_length=30)),
                ("quantity", models.IntegerField()),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "movement_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="parties.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_on_hand", models.PositiveIntegerField(default=0)),
                ("qty_reserved", models.PositiveIntegerField(default=0)),
                ("qty_available", models.PositiveIntegerField(default=0)),
                (
                    "avg_cost_cad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="products.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="parties.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="stock_transfer_quantity_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("source_warehouse", models.F("destination_warehouse")),
                    _negated=True,
                ),
                name="stock_transfer_different_warehouses",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity", 0), _negated=True),
                name="stock_movement_quantity_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("product", "warehouse"),
                name="unique_inventory_product_warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                check=models.Q(("qty_reserved__lte", models.F("qty_on_hand"))),
                name="inventory_reserved_lte_on_hand",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "qty_available",
                        django.db.models.expressions.CombinedExpression(
                            models.F("qty_on_hand"), "-", models.F("qty_reserved")
                        ),
                    )
                ),
                name="inventory_available_matches_stock",
            ),
        ),
    ]
