# Generated by Django 6.1 on 2026-08-14 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('settlement_status', models.CharField(default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_code', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='finance.financialaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='UNPAID', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_irr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total_irr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
