# Generated by Django 4.2.30 on 2026-08-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_remove_payment_customer_payment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customerreceivable",
            table="customer_receivables",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payments",
        ),
        migrations.AlterModelTable(
            name="sale",
            table="sales",
        ),
        migrations.AlterModelTable(
            name="saleitem",
            table="sale_items",
        ),
    ]
