# Generated by Django 4.2.30 on 2026-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_customerreceivable_table_alter_payment_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency_code",
            field=models.CharField(max_length=3),
        ),
    ]
