# Generated by Django 4.2.30 on 2026-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_payment_currency_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerreceivable",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="settlement_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="line_total_irr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddConstraint(
            model_name="customerreceivable",
            constraint=models.CheckConstraint(
                check=models.Q(("original_amount__gte", 0)),
                name="receivable_original_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreceivable",
            constraint=models.CheckConstraint(
                check=models.Q(("paid_amount__gte", 0)), name="receivable_paid_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreceivable",
            constraint=models.CheckConstraint(
                check=models.Q(("remaining_amount__gte", 0)),
                name="receivable_remaining_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreceivable",
            constraint=models.CheckConstraint(
                check=models.Q(("paid_amount__lte", models.F("original_amount"))),
                name="receivable_paid_lte_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="payment_amount_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("total_amount__gte", 0)),
                name="sale_total_amount_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("total_paid__gte", 0)), name="sale_total_paid_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("total_debt__gte", 0)), name="sale_total_debt_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("total_paid__lte", models.F("total_amount"))),
                name="sale_paid_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="sale_item_quantity_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price_irr__gte", 0)),
                name="sale_item_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                check=models.Q(("line_total_irr__gte", 0)),
                name="sale_item_total_gte_zero",
            ),
        ),
    ]
