# Generated by Django 4.2.30 on 2026-08-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0002_remove_supplier_contact_info_supplier_email_and_more"),
        ("sales", "0005_alter_customerreceivable_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="parties.warehouse",
            ),
        ),
    ]
