# Generated by Django 4.2.30 on 2026-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_saleitem_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cad_rate_irr_per_cad",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="line_cogs_cad",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="line_cogs_irr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="unit_cost_cad_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("cad_rate_irr_per_cad__isnull", True),
                    ("cad_rate_irr_per_cad__gt", 0),
                    _connector="OR",
                ),
                name="sale_cad_rate_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("unit_cost_cad_snapshot__isnull", True),
                    ("unit_cost_cad_snapshot__gte", 0),
                    _connector="OR",
                ),
                name="sale_item_cost_snapshot_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("line_cogs_cad__isnull", True),
                    ("line_cogs_cad__gte", 0),
                    _connector="OR",
                ),
                name="sale_item_cogs_cad_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("line_cogs_irr__isnull", True),
                    ("line_cogs_irr__gte", 0),
                    _connector="OR",
                ),
                name="sale_item_cogs_irr_positive_or_null",
            ),
        ),
    ]
