# Generated by Django 4.2.30 on 2026-08-15 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_number", models.CharField(max_length=50)),
                (
                    "purchase_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("purchase_currency", models.CharField(max_length=3)),
                (
                    "exchange_rate_to_cad",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "shipping_cost_irr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "customs_cost_irr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "other_costs_irr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax_irr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "overall_discount_irr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paying_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_purchases",
                        to="parties.financialaccount",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="parties.supplier",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="parties.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "purchases",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "row_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "landed_cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="products.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchase",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_items",
            },
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="purchase_item_quantity_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_cost__gte", 0)),
                name="purchase_item_unit_cost_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                check=models.Q(("row_discount__gte", 0)),
                name="purchase_item_discount_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                check=models.Q(("landed_cost_per_unit__gte", 0)),
                name="purchase_item_landed_cost_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                check=models.Q(("line_total__gte", 0)),
                name="purchase_item_line_total_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("exchange_rate_to_cad__gt", 0)),
                name="purchase_exchange_rate_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("shipping_cost_irr__gte", 0)),
                name="purchase_shipping_cost_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("customs_cost_irr__gte", 0)),
                name="purchase_customs_cost_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("other_costs_irr__gte", 0)),
                name="purchase_other_costs_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("tax_irr__gte", 0)), name="purchase_tax_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("overall_discount_irr__gte", 0)),
                name="purchase_discount_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("paid_amount__gte", 0)),
                name="purchase_paid_amount_gte_zero",
            ),
        ),
    ]
