# Generated by Django 4.2.30 on 2026-08-16 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency_code", models.CharField(max_length=3)),
                ("payment_type", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_payments",
                        to="parties.financialaccount",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="procurement.purchase",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_payments",
            },
        ),
        migrations.AddConstraint(
            model_name="purchasepayment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="purchase_payment_amount_gt_zero",
            ),
        ),
    ]
