# Generated by Django 4.2.30 on 2026-09-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_purchasepayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="irr_per_cad",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                check=models.Q(("irr_per_cad__gt", 0)),
                name="purchase_irr_per_cad_gt_zero",
            ),
        ),
    ]
